news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.articulo-titulo a'
      article_body: ''
      article_title: ''
  fincaraiz:
    url: https://www.fincaraiz.com.co/finca-raiz
    queries:
      homepage_article_links: '.advert .title-grid a'
      article_body: '.advertSurface'
      article_title: '.detailheader h1'

  eltiempo:
    url: https://eltiempo.com
    queries:
      homepage_article_links: '.title-container a'
      article_body: '.contenido'
      article_title: '.titulo'
